import type { Metadata } from "next";
import { Amaranth, Inter, Lato, Titillium_Web, Urbanist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils";

const lato = Lato({ weight: "400", subsets: ["latin"] });
const urbanist = Urbanist({ weight: "400", subsets: ["latin"] });
const titillium_Web = Titillium_Web({ weight: "400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={cn(titillium_Web.className, "bg-background")}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body>

    </html>
  );
}
